version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    run-as: root
    commands:
      - echo This is a installation
      - wget https://services.gradle.org/distributions/gradle-6.7-all.zip
      - unzip -d /opt/gradle gradle-6.7-all.zip

  pre_build:
    commands:
      - echo Java Version
      - java -version

  build:
    commands:
      - echo Starting build `date`
      - echo Current directory is `pwd`
      - whereis gradle
      - which gradle
      - /opt/gradle/gradle-6.7/bin/gradle -version
      - /opt/gradle/gradle-6.7/bin/gradle clean
      - /opt/gradle/gradle-6.7/bin/gradle build

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - build/libs/aws-*-all.jar
