version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11

  pre_build:
    commands:
      - echo skipped on `date`
      - echo Versao do gradle
      - gradle -version
      - apt install gradle -y
      - echo Versao do Gradle

  build:
    commands:
      - echo Gradle Build on `date`
      - java -version
      - gradle build

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - build/libs/aws-*-all.jar
